version: '3.7'

services:
  api-php:
    env_file:
      - .env.dev
    volumes:
      - ./docker/php/rootfs/usr/local/etc/php/api-pewpui.ini-development:/usr/local/etc/php/conf.d/api-pewpui.ini:ro
      - ./:/srv/api:rw,cached

  bo-nginx:
    volumes:
      - ./public:/srv/api/public:ro
