version: '3.7'

services:
  tests:
    image: codeception/codeception
    depends_on:
      - bo-nginx
    environment:
      - ACCEPTANCE_TEST_HOST=http://bo-nginx
    volumes:
      - .:/project:rw,cached
    networks:
      - front
      - back
